# --- Image de base ---
FROM python:3.10-slim

# --- Variables d'environnement ---
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# --- Définir le répertoire de travail ---
WORKDIR /app

# --- Installer les dépendances système nécessaires ---
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# --- Copier requirements.txt ---
COPY app/requirements-fastapi.txt /app/requirements.txt

# --- Installer pip et les packages Python ---
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip check

# --- Copier le code source ---
COPY app /app

# --- Exposer le port de l'application ---
EXPOSE 8000

# --- Commande par défaut pour lancer l'application ---
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
