# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNQQvle98sVXbDPYIXFCHgwtbCiuNCXC
"""

import requests
from bs4 import BeautifulSoup
import json
import time
import os

headers = {"User-Agent": "Mozilla/5.0"}

country_urls = {
    "France": "https://fr.trustpilot.com/review/www.showroomprive.com?page={}",
    "Spain": "https://es.trustpilot.com/review/www.showroomprive.com?page={}",
    "Italy": "https://it.trustpilot.com/review/www.showroomprive.com?page={}"
}

NUM_PAGES = 1000
all_reviews = []

# Création du dossier de debug si nécessaire
os.makedirs("debug_json", exist_ok=True)

# Flag pour n’afficher qu’une seule fois le debug par pays
debug_done = {country: False for country in country_urls.keys()}

for country, template in country_urls.items():
    stop_country = False

    for page in range(1, NUM_PAGES + 1):
        if stop_country:
            break

        url = template.format(page)
        resp = requests.get(url, headers=headers)
        soup = BeautifulSoup(resp.text, "html.parser")

        # Extraction du JSON embarqué
        script = soup.find("script", id="__NEXT_DATA__")
        if not script:
            print(f"pas de script JSON trouvé à la page {page}")
            stop_country = True
            break

        try:
            data = json.loads(script.string)
            page_props = data.get("props", {}).get("pageProps", {})

            # Sortie anticipée si pas d'avis
            reviews = page_props.get("reviews", [])
            if not reviews:
                print(f"pas d'avis trouvés à la page {page}, arrêt pour {country}")
                debug_filename = f"debug_json/debug_page_{country.replace(' ', '_')}_{page}.json"
                with open(debug_filename, "w", encoding="utf-8") as f:
                    json.dump(page_props, f, ensure_ascii=False, indent=2)
                stop_country = True
                break

            # Parcours des avis
            for rev in reviews:
                reply = rev.get("reply") or {}
                texte = reply.get("message", "")
                date = reply.get("publishedDate", "")

                all_reviews.append({
                    "Titre_avis": rev.get("title", ""),
                    "Contenu (texte)": rev.get("text", ""),
                    "Nombre_etoile": rev.get("rating"),
                    "Date_avis": rev.get("dates", {}).get("publishedDate", ""),
                    "Pays": country,
                    "langue": rev.get("language", ""),
                    "Reponse_entreprise (OUI/NON)": "OUI" if texte else "NON",
                    "Texte_entreprise": texte,
                    "Date_reponse_entreprise": date
                })

        except Exception as e:
            print(f"erreur JSON à la page {page}: {e}")
            debug_filename = f"debug_json/debug_raw_{country.replace(' ', '_')}_{page}.txt"
            with open(debug_filename, "w", encoding="utf-8") as f:
                f.write(script.string)
            stop_country = True
            break

        time.sleep(2)

# Enregistrement final des avis
with open("reviews.json", "w", encoding="utf-8") as f:
    json.dump(all_reviews, f, ensure_ascii=False, indent=2)

print(f"\n{len(all_reviews)} avis extraits et enregistrés dans 'reviews.json'")